### ISSUE TITLE
Build Prod Failed. Error encountered resolving symbol values statically. Function calls are not supported.

### ISSUE THREAD

**Issue by deep113** [NextFaze/ionic-manup#3]
```

D:\works\2017\feb\this\ionic-manup-master\manup-demo>ionic run android --prod

> ionic-hello-world@ ionic:build D:\works\2017\feb\this\ionic-manup-master\manup-demo
> ionic-app-scripts build "--prod"

[14:51:50]  ionic-app-scripts 1.0.0
[14:51:50]  build prod started ...
[14:51:50]  clean started ...                                                                                           [14:51:50]  clean finished in 15 ms
[14:51:50]  copy started ...
[14:51:50]  ngc started ...
[14:51:52]  build prod failed: Error encountered resolving symbol values statically. Function calls are not supported.
            Consider replacing the function or lambda with a reference to an exported function, resolving symbol
            AppModule in D:/works/2017/feb/this/ionic-manup-master/manup-demo/src/app/app.module.ts, resolving symbol
            AppModule in D:/works/2017/feb/this/ionic-manup-master/manup-demo/src/app/app.module.ts
[14:51:52]  ionic-app-script task: "build"
[14:51:52]  Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider
            replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in
            D:/works/2017/feb/this/ionic-manup-master/manup-demo/src/app/app.module.ts, resolving symbol AppModule in
            D:/works/2017/feb/this/ionic-manup-master/manup-demo/src/app/app.module.ts
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in D:/works/2017/feb/this/ionic-manup-master/manup-demo/src/app/app.module.ts, resolving symbol AppModule in D:/works/2017/feb/this/ionic-manup-master/manup-demo/src/app/app.module.ts
    at simplifyInContext (D:\works\2017\feb\this\ionic-manup-master\manup-demo\node_modules\@angular\compiler-cli\src\static_reflector.js:475:23)                                                                                                   at StaticReflector.simplify (D:\works\2017\feb\this\ionic-manup-master\manup-demo\node_modules\@angular\compiler-cli\src\static_reflector.js:478:22)
    at StaticReflector.annotations (D:\works\2017\feb\this\ionic-manup-master\manup-demo\node_modules\@angular\compiler-cli\src\static_reflector.js:60:36)
    at NgModuleResolver.resolve (D:\works\2017\feb\this\ionic-manup-master\manup-demo\node_modules\@angular\compiler\bundles\compiler.umd.js:14261:46)                                                                                              at CompileMetadataResolver._loadNgModuleMetadata (D:\works\2017\feb\this\ionic-manup-master\manup-demo\node_modules\@angular\compiler\bundles\compiler.umd.js:14646:45)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (D:\works\2017\feb\this\ionic-manup-master\manup-demo\node_modules\@angular\compiler\bundles\compiler.umd.js:14636:23)                                                                   at addNgModule (D:\works\2017\feb\this\ionic-manup-master\manup-demo\node_modules\@angular\compiler\bundles\compiler.umd.js:12944:43)
    at D:\works\2017\feb\this\ionic-manup-master\manup-demo\node_modules\@angular\compiler\bundles\compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (D:\works\2017\feb\this\ionic-manup-master\manup-demo\node_modules\@angular\compiler\bundles\compiler.umd.js:12956:28)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:build" "--" "--prod"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ ionic:build: `ionic-app-scripts build "--prod"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ ionic:build script 'ionic-app-scripts build "--prod"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build "--prod"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\works\2017\feb\this\ionic-manup-master\manup-demo\npm-debug.log
```

**Comment by MichaelMarner** [comment]
Thanks for the bug reoort, I'll fix AoT builds tomorrow

**Comment by MichaelMarner** [comment]
Version `0.0.4`, just published to npm, includes metadata needed for AoT production Ionic builds. Have tested in the included demo app on iOS. Please let me know if you run into problems.

**Comment by deep113** [comment]
Thank you.
